import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

const rubik = Vazirmatn({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${rubik.variable}  antialiased  w-screen h-screen flex justify-center items-center  `}
      >
        <Toaster position="top-center" richColors />
        {children}


      </body>
    </html>
  );
}
